### ISSUE TITLE
Some pages are not available

### ISSUE THREAD

**Issue by CyanFroste** [DiamondMiner88/nhentai#13]
@DiamondMiner88 Do you know why some pages throw `does not exist` like...

this works -> https://nhentai.net/api/galleries/search?query=*&page=5&sort=popular

but this doesn't -> https://nhentai.net/api/galleries/search?query=*&page=4&sort=popular

**Comment by DiamondMiner88** [comment]
No clue, someone made an issue about this last year and it seemed to resolve itself.
The only thing that worked immediately is providing auth cookies but that isn't a viable long term solution

**Comment by CyanFroste** [comment]
It seems it's only happening when we query `*` ... Rip.
