### ISSUE TITLE
Add a method to show `homepage` / `list all` doujins by setting `query` value to `*` in search.

### ISSUE THREAD

**Issue by CyanFroste** [DiamondMiner88/nhentai#2]

**Comment by DiamondMiner88** [comment]
The homepage sorts by most recently uploaded, which is also the default behavior on the api. If you search with the sort paramater as `SortMethods.RECENT` or no paramater at all it'll get what you're aiming for. I'll also document this once I add a proper documentation.

**Comment by CyanFroste** [comment]
Your api doesn't have a `homepage` method. `SortMethods.RECENT` should be passed to `search`, but it requires a `query`. I just realize I mistakenly specified `query` as `sort`. 
```
homepage(page, sort) {
    return this.search('*', page, sort);
}
```

will do. I guess.

**Comment by DiamondMiner88** [comment]
I did some testing and got inconsistent results. The home page shows results that do not appear when searching for `*`, and vice-versa. Not really sure what to do here.
