### ISSUE TITLE
Sort by `recent` isn't working when query=*, which is odd, since it was working yesterday. I think it's a fault with their api. 

### ISSUE THREAD

**Issue by CyanFroste** [DiamondMiner88/nhentai#3]
Rest of the sorting methods are working for query `*`. `recent` is working for any other query too. 

p.s. I can fork and contribute if you let me in on how you got api endpoints. thanks. I don't wanna go back to scraping.

**Comment by CyanFroste** [comment]
It was a fault on their end. It's fixed now.

**Comment by DiamondMiner88** [comment]
> p.s. I can fork and contribute if you let me in on how you got api endpoints. thanks. I don't wanna go back to scraping.

I just looked at a lot of libraries to find available endpoints. I didn't find and new ones myself sadly.
