### ISSUE TITLE
Export the types

### ISSUE THREAD

**Issue by Tenpi** [DiamondMiner88/nhentai#4]
Hello, I'm a TypeScript user and noticed that your package is only exporting "API" and "SortMethods".

It would be helpful if you could export all your classes and interfaces here:
https://github.com/DiamondMiner88/nhentai/blob/main/src/index.ts

My use case is to type function parameters.
```ts
const getDoujin = (doujin: Doujin) => {}
```

**Comment by Tenpi** [comment]
Also, the typings for the tag type needs to be more specific then `string`... 

I would prefer it if you separated the tags such as `doujin.artists`, `doujin.characters`, etc. because I have to search through the tags manually just to find the artist.

**Comment by DiamondMiner88** [comment]
> It would be helpful if you could export all your classes and interfaces here:

k

> I would prefer it if you separated the tags such as doujin.artists, doujin.characters, etc. because I have to search through the tags manually just to find the artist.

Yes, I also wanted to do something like that.
The only downside is it will confuse existing users as `<Doujin>.tags` would now only be be the `tag` type of all tags.
On release I'll make a changelog.

**Comment by DiamondMiner88** [comment]
@Tenpi Here's a draft of the tag sorting: #5 
Any thoughts?

**Comment by Tenpi** [comment]
It's still a bit ugly, I will have to do `doujin.tags.artists().map(t => t.name)` which is barely an improvement over `doujin.tags.filter((t) => t.type === "artist").map(t => t.name)`.

I'm not a fan of your tag class anyways because it contains way too much useless info. The tags should just be an array containing just the names, and if you want all the detailed info you can provide a method like `nhentai.getTagInfo(tag)`. 

The ideal would be to have `doujin.artists`, `doujin.groups` etc. that is just the array of names, since that is what you want. At the very least I would prefer `doujin.artists.map(t => t.name)` if you don't want to get rid of your tag class.

**Comment by DiamondMiner88** [comment]
IMO, sorting only the identifiers just makes it confusing. I'll just go ahead and merge since I haven't thought of anything better.

**Comment by Tenpi** [comment]
Don't like it. Will just write my own library when I get around to it.
