### ISSUE TITLE
Api returning wrong thumbnail link.

### ISSUE THREAD

**Issue by CyanFroste** [DiamondMiner88/nhentai#8]
It should return something like `https://t.nhentai.net/galleries/1553654/thumb.png`  instead of `https://t.nhentai.net/galleries/1553654/thumbnail.png`

**Comment by CyanFroste** [comment]
I had to freaking review my whole previous project to find such a small mistake. :/

**Comment by DiamondMiner88** [comment]
My bad, I see what I did wrong.
I'll release a patch in around an hour.

**Comment by CyanFroste** [comment]
Alrightt!

**Comment by CyanFroste** [comment]
Might as well clone your repo instead of using via npm
